import json
import os
from pathlib import Path

from dotenv import load_dotenv

# Load .env before importing any module that reads model names from environment variables.
ROOT = Path(__file__).parent
load_dotenv(dotenv_path=ROOT / ".env")

from src.file_loader import load_document, load_text_file, save_text, is_supported_document
from src.extractor import run_extraction
from src.json_utils import parse_json, write_json
from src.llm_clients import call_openai, call_claude


DATA_DIR = ROOT / "data"
OUTPUT_DIR = ROOT / "outputs"
PROMPT_DIR = ROOT / "prompts"
GENERIC_EXTRACTION_PROMPT = PROMPT_DIR / "extract_document.txt"
SUPPORTED_PROVIDERS = {"openai", "claude"}


def cache_enabled() -> bool:
    """
    Reuse existing valid JSON outputs by default.

    This protects you from paying again if the pipeline crashes after expensive
    extraction/profile stages. Set USE_CACHE=false in .env if you intentionally
    want a completely fresh run.
    """
    value = os.getenv("USE_CACHE", "true").strip().lower()
    return value not in {"0", "false", "no", "off"}


def require_prompt_text(prompt_path: Path, prompt_name: str) -> str:
    """Fail fast if a required prompt file is missing or empty."""
    text = load_text_file(str(prompt_path))
    if not text.strip():
        raise FileNotFoundError(
            f"Required prompt is missing or empty: {prompt_path} ({prompt_name}). "
            "Stopping before any expensive API call."
        )
    return text


def validate_provider(provider: str) -> str:
    """Normalize and validate provider names used across the pipeline."""
    provider = provider.strip().lower()

    if provider not in SUPPORTED_PROVIDERS:
        raise ValueError(
            f"Unsupported provider: {provider}. "
            f"Supported providers are: {sorted(SUPPORTED_PROVIDERS)}"
        )

    return provider


def provider_output_dir(provider: str) -> Path:
    """
    Return the provider-specific output directory.

    All model-generated files for OpenAI go under outputs/openai/.
    All model-generated files for Claude go under outputs/claude/.
    """
    provider = validate_provider(provider)
    return OUTPUT_DIR / provider


def provider_extraction_dir(provider: str) -> Path:
    """Return the provider-specific extraction directory."""
    return provider_output_dir(provider) / "extractions"


def shared_output_dir() -> Path:
    """
    Return the shared output directory.

    Files that are not generated by a specific model/provider go here.
    Example: SOURCE_INDEX, because it only maps DOC IDs to original files.
    """
    return OUTPUT_DIR / "shared"


def discover_documents(data_dir: Path = DATA_DIR) -> list[Path]:
    """Return all supported user documents inside data/, independent of file name."""
    if not data_dir.exists():
        return []

    return sorted(
        path
        for path in data_dir.rglob("*")
        if is_supported_document(path)
    )


def source_id_for(index: int) -> str:
    return f"DOC-{index:03d}"


def build_source_index(documents: list[Path]) -> list[dict]:
    """Create a stable mapping between DOC IDs and input files."""
    return [
        {
            "source_id": source_id_for(index),
            "file_path": str(path.relative_to(ROOT)),
            "file_type": path.suffix.lower(),
        }
        for index, path in enumerate(documents, start=1)
    ]


def save_source_index(source_index: list[dict]) -> None:
    """Save SOURCE_INDEX in a shared folder because it belongs to both providers."""
    output_path = shared_output_dir() / "00_source_index.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_json(str(output_path), source_index)


def load_cached_json(json_path: Path, stage_name: str):
    """Return cached JSON when available and valid; otherwise return None."""
    if not cache_enabled() or not json_path.exists():
        return None

    try:
        parsed = parse_json(json_path.read_text(encoding="utf-8"))
        print(f"Reusing cached result for {stage_name}: {json_path.relative_to(ROOT)}")
        return parsed
    except Exception as exc:
        print(f"Cache ignored for {stage_name}; existing JSON is invalid: {json_path}")
        print(exc)
        return None


def save_raw_and_json(raw_output: str, json_path: Path):
    json_path.parent.mkdir(parents=True, exist_ok=True)
    raw_path = json_path.with_suffix(".raw.txt")
    save_text(str(raw_path), raw_output)

    try:
        parsed = parse_json(raw_output)
        write_json(str(json_path), parsed)
        return parsed
    except Exception as e:
        print(f"\nJSON ERROR in: {json_path.name}")
        print(e)
        print(f"\nRaw output saved to:\n{raw_path}")
        return None


def require_json_result(value, stage_name: str):
    """Stop the pipeline early if a model response could not be parsed as JSON."""
    if value is None:
        raise ValueError(
            f"{stage_name} did not return valid JSON. "
            "Check the matching .raw.txt file in outputs/ before continuing."
        )
    return value


def run_json_stage(stage_name: str, output_path: Path, api_call):
    """
    Run one expensive model stage safely.

    If a valid JSON output already exists and USE_CACHE is enabled, reuse it.
    Otherwise call the model, save raw output, parse JSON, and fail fast on errors.
    """
    cached = load_cached_json(output_path, stage_name)
    if cached is not None:
        return cached

    return require_json_result(
        save_raw_and_json(api_call(), output_path),
        stage_name,
    )


def prepare_sources() -> tuple[list[Path], list[dict]]:
    """
    Discover input documents once and create one shared SOURCE_INDEX.

    The SOURCE_INDEX should remain common for both providers so DOC-001, DOC-002,
    etc. always point to the same original files.
    """
    documents = discover_documents()

    if not documents:
        raise FileNotFoundError(
            "No supported documents found in the data/ folder. "
            "Add files such as .pdf, .tex, .txt, .md, .docx, .json, or .csv."
        )

    source_index = build_source_index(documents)
    save_source_index(source_index)

    return documents, source_index


def validate_required_prompts() -> None:
    """
    Check all prompt files before the first API call.

    This avoids wasting money on a run where one of the later prompt files is
    missing or empty.
    """
    required_prompts = {
        "generic extraction": GENERIC_EXTRACTION_PROMPT,
        "synthesis": PROMPT_DIR / "synthesize_digital_twin.txt",
        "review": PROMPT_DIR / "review_profile.txt",
        "improvement": PROMPT_DIR / "improve_profile.txt",
    }

    for prompt_name, prompt_path in required_prompts.items():
        require_prompt_text(prompt_path, prompt_name)


def run_document_extractions(provider: str, documents: list[Path]) -> list[dict]:
    """
    Extract evidence from every source document with the selected provider.

    Important:
    - OpenAI extraction is stored under outputs/openai/extractions/.
    - Claude extraction is stored under outputs/claude/extractions/.
    - The two providers never share extraction outputs.
    """
    provider = validate_provider(provider)
    extraction_output_dir = provider_extraction_dir(provider)
    extraction_output_dir.mkdir(parents=True, exist_ok=True)

    source_extractions = []

    print()
    print(f"Running document extraction with provider: {provider}")

    for index, path in enumerate(documents, start=1):
        source_id = source_id_for(index)
        output_path = extraction_output_dir / f"{index:02d}_{source_id.lower()}_extraction.json"

        print(f"Extracting {source_id} with {provider}: {path.relative_to(DATA_DIR)}")

        cached = load_cached_json(output_path, f"Extraction for {source_id} with {provider}")
        if cached is not None:
            source_extractions.append(
                {
                    "source_id": source_id,
                    "provider": provider,
                    "extraction_file": str(output_path.relative_to(ROOT)),
                    "data": cached,
                }
            )
            continue

        document_text = load_document(str(path))

        if not document_text.strip():
            print(f"Skipping empty or unreadable document: {path}")
            continue

        raw_output = run_extraction(
            prompt_path=str(GENERIC_EXTRACTION_PROMPT),
            source_id=source_id,
            document_text=document_text,
            provider=provider,
        )

        parsed = save_raw_and_json(raw_output, output_path)
        parsed = require_json_result(parsed, f"Extraction for {source_id} with {provider}")

        source_extractions.append(
            {
                "source_id": source_id,
                "provider": provider,
                "extraction_file": str(output_path.relative_to(ROOT)),
                "data": parsed,
            }
        )

    return source_extractions


def call_provider(provider: str, prompt: str) -> str:
    provider = validate_provider(provider)

    if provider == "claude":
        return call_claude(prompt)

    return call_openai(prompt)


def synthesize_with_provider(source_index: list[dict], source_extractions: list[dict], provider: str):
    provider = validate_provider(provider)
    synthesis_prompt = require_prompt_text(
        PROMPT_DIR / "synthesize_digital_twin.txt",
        "synthesis",
    )

    prompt = f"""
{synthesis_prompt}

====================
SOURCE_INDEX
====================
{json.dumps(source_index, ensure_ascii=False, indent=2)}

====================
SOURCE_EXTRACTIONS
====================
{json.dumps(source_extractions, ensure_ascii=False, indent=2)}
"""

    return call_provider(provider, prompt)


def review_profile(
    reviewer_provider: str,
    target_profile: dict,
    source_index: list[dict],
    reviewer_source_extractions: list[dict],
):
    """
    Review a profile using the reviewer's own extracted evidence.

    Example:
    - GPT reviews Claude profile using OpenAI extractions.
    - Claude reviews GPT profile using Claude extractions.
    """
    reviewer_provider = validate_provider(reviewer_provider)
    review_prompt = require_prompt_text(PROMPT_DIR / "review_profile.txt", "review")

    prompt = f"""
{review_prompt}

====================
SOURCE_INDEX
====================
{json.dumps(source_index, ensure_ascii=False, indent=2)}

====================
SOURCE_EXTRACTIONS
====================
{json.dumps(reviewer_source_extractions, ensure_ascii=False, indent=2)}

====================
PROFILE_TO_REVIEW
====================
{json.dumps(target_profile, ensure_ascii=False, indent=2)}
"""

    return call_provider(reviewer_provider, prompt)


def improve_profile(
    provider: str,
    profile_v1: dict,
    review: dict,
    source_index: list[dict],
    provider_source_extractions: list[dict],
):
    """
    Improve a provider's profile using:
    - that provider's own V1 profile,
    - the other model's review,
    - that provider's own extracted evidence.
    """
    provider = validate_provider(provider)
    improve_prompt = require_prompt_text(PROMPT_DIR / "improve_profile.txt", "improvement")

    prompt = f"""
{improve_prompt}

====================
PROFILE_V1
====================
{json.dumps(profile_v1, ensure_ascii=False, indent=2)}

====================
REVIEW_FROM_OTHER_MODEL
====================
{json.dumps(review, ensure_ascii=False, indent=2)}

====================
SOURCE_INDEX
====================
{json.dumps(source_index, ensure_ascii=False, indent=2)}

====================
SOURCE_EXTRACTIONS
====================
{json.dumps(provider_source_extractions, ensure_ascii=False, indent=2)}
"""

    return call_provider(provider, prompt)


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    shared_output_dir().mkdir(parents=True, exist_ok=True)
    provider_output_dir("openai").mkdir(parents=True, exist_ok=True)
    provider_output_dir("claude").mkdir(parents=True, exist_ok=True)

    validate_required_prompts()
    documents, source_index = prepare_sources()

    print()
    print(f"USE_CACHE={cache_enabled()}")
    print(f"Documents discovered: {len(documents)}")
    print("Expected model calls on a fresh run:")
    print(f"- Extractions: {len(documents)} OpenAI + {len(documents)} Claude")
    print("- Profile stages: 3 OpenAI + 3 Claude")
    print(f"- Total fresh calls: {2 * len(documents) + 6}")

    # Each model extracts the original documents independently.
    openai_source_extractions = run_document_extractions("openai", documents)
    claude_source_extractions = run_document_extractions("claude", documents)

    print()
    print("Stage 1 - GPT Profile V1")
    gpt_v1 = run_json_stage(
        "GPT Profile V1",
        provider_output_dir("openai") / "05_candidate_profile_gpt_v1.json",
        lambda: synthesize_with_provider(source_index, openai_source_extractions, "openai"),
    )

    print("Stage 1 - Claude Profile V1")
    claude_v1 = run_json_stage(
        "Claude Profile V1",
        provider_output_dir("claude") / "06_candidate_profile_claude_v1.json",
        lambda: synthesize_with_provider(source_index, claude_source_extractions, "claude"),
    )

    print("Stage 2 - GPT Review Claude")
    gpt_review = run_json_stage(
        "GPT Review Claude",
        provider_output_dir("openai") / "07_gpt_review_of_claude.json",
        lambda: review_profile("openai", claude_v1, source_index, openai_source_extractions),
    )

    print("Stage 2 - Claude Review GPT")
    claude_review = run_json_stage(
        "Claude Review GPT",
        provider_output_dir("claude") / "08_claude_review_of_gpt.json",
        lambda: review_profile("claude", gpt_v1, source_index, claude_source_extractions),
    )

    print("Stage 3 - GPT Profile V2")
    run_json_stage(
        "GPT Profile V2",
        provider_output_dir("openai") / "09_candidate_profile_gpt_v2.json",
        lambda: improve_profile("openai", gpt_v1, claude_review, source_index, openai_source_extractions),
    )

    print("Stage 3 - Claude Profile V2")
    run_json_stage(
        "Claude Profile V2",
        provider_output_dir("claude") / "10_candidate_profile_claude_v2.json",
        lambda: improve_profile("claude", claude_v1, gpt_review, source_index, claude_source_extractions),
    )

    print()
    print("Pipeline complete")
    print()
    print("Shared files:")
    print("outputs/shared/00_source_index.json")
    print()
    print("OpenAI files:")
    print("outputs/openai/extractions/")
    print("outputs/openai/05_candidate_profile_gpt_v1.json")
    print("outputs/openai/07_gpt_review_of_claude.json")
    print("outputs/openai/09_candidate_profile_gpt_v2.json")
    print()
    print("Claude files:")
    print("outputs/claude/extractions/")
    print("outputs/claude/06_candidate_profile_claude_v1.json")
    print("outputs/claude/08_claude_review_of_gpt.json")
    print("outputs/claude/10_candidate_profile_claude_v2.json")
    print()
    print("Review these files manually:")
    print("outputs/openai/09_candidate_profile_gpt_v2.json")
    print("outputs/claude/10_candidate_profile_claude_v2.json")
    print()
    print("Then manually create candidate_profile.json for Career Agent.")


if __name__ == "__main__":
    main()